name: Release Wheel Files

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Download Flask Wheel
        run: |
         pip download flask --only-binary=:all:  --no-deps -d ./wheels

      - name: Create Release and Upload wheels to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: wheels/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true