name: Release Wheel Files

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Download Flask Wheel
        run: |
          pip download flask --only-binary=:all: --no-deps

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: t1
          release_name: Release t1
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
